include: package:lints/recommended.yaml

analyzer:
  exclude:
    - tool/fixtures/**
    - test/temp_*/
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  plugins:
    - zuke_analyzer

linter:
  rules:
    avoid_print: false
    curly_braces_in_flow_control_structures: true
    dangling_library_doc_comments: true
