name: nightly

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  shopping-cart-assurance:
    uses: ./.github/workflows/flutter-example-assurance.yml
    with:
      profile: merge
      changed-since: HEAD~1
      example-root: examples/shopping_cart
      package-name: shopping_cart
      require-history: false
  todo-app-assurance:
    uses: ./.github/workflows/flutter-example-assurance.yml
    with:
      profile: merge
      changed-since: HEAD~1
      example-root: examples/todo_app
      package-name: todo_app
      require-history: false
  calculator-product-assurance:
    uses: ./.github/workflows/calculator-product-assurance.yml
    with:
      profile: nightly
