name: pr

on:
  pull_request:

jobs:
  shopping-cart-assurance:
    uses: ./.github/workflows/flutter-example-assurance.yml
    with:
      profile: pullRequest
      changed-since: ${{ github.event.pull_request.base.sha }}
      example-root: examples/shopping_cart
      package-name: shopping_cart
      require-history: false
  todo-app-assurance:
    uses: ./.github/workflows/flutter-example-assurance.yml
    with:
      profile: pullRequest
      changed-since: ${{ github.event.pull_request.base.sha }}
      example-root: examples/todo_app
      package-name: todo_app
      require-history: false
  calculator-product-assurance:
    uses: ./.github/workflows/calculator-product-assurance.yml
    with:
      profile: pullRequest
      prepare_lock: true
